### ISSUE TITLE
output script leaks the name of the interpreter

### ISSUE THREAD

**Issue by allenbh** [rolandshoemaker/raziel#2]
An unauthorized viewer of the encrypted data can identify which interpreter will be used.

**Comment by rolandshoemaker** [comment]
True, this could be fixed by also encrypting the interpreter (perhaps on a line by itself before/after the input script) and then adding a step to the decryption pipeline to strip the interpreter line and run it...

**Comment by allenbh** [comment]
Either way, the decrypted payload has to go somewhere, be it bash, perl, cat... or anything that reads stdin.  You could encrypt a perl script that invokes a bash subprocess, and pass the decrypted payload to perl, or you could encrypt a bash script that invokes perl, and pass the decrypted payload to bash.  I don't see any solution better than that.

So, closing this... functions as designed?
